<?php
/**
 * Fontis Australia Extension for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $block Fontis\Australia\Block\Payment\BPAY\Details */ ?>

<div id="bpay" style="border: 2px solid rgb(16, 32, 75); margin: 0 0 10px; padding: 6px; width: 238px; font-family: Arial,Helvetica,sans-serif; background-color: rgb(255, 255, 255);">
    <div class="bpayLogo" style="border: 2px solid rgb(20, 44, 97); width: 55px; height: 87px; float: left;">
        <img alt="BPAY" src="<?php echo $block->getBpayLogoUrl(); ?>" height="82" width="51">
    </div>
    <div class="customerReferenceBox" style="border: 2px solid rgb(20, 44, 97); padding: 0 8px; height: 87px; width: 158px; margin-left: 60px; margin-bottom: 4px;">
        <p class="customerReferenceBoxText" style="font-size: 13px; text-transform: capitalize; color: rgb(20, 44, 97); white-space: nowrap; line-height: 22px; font-weight: normal;">
            <b><?php echo __("Biller Code"); ?></b>: <?php echo $block->getBillerCode(); ?><br>
            <b><?php echo __("Ref"); ?></b>: <?php echo $block->getCustomerRef(); ?><br>
        </p>
    </div>
    <div>
        <p class="billerTextHeading" style="font-size: 11px; text-transform: capitalize; color: rgb(20, 44, 97); white-space: nowrap; line-height: 20px; font-weight: bold;"><?php echo $block->escapeHtml(__("Telephone & Internet Banking — BPAY®")); ?></p>
        <p class="billerText" style="font-size: 11px; color: rgb(20, 44, 97);"><?php echo $block->escapeHtml($block->getBillerText()); ?></p>
    </div>
</div>
