<?php
/**
 * Fontis Australia Extension for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * http://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @copyright  Copyright (c) 2016 Fontis Pty. Ltd. (http://www.fontis.com.au)
 * @license    http://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $block \Fontis\Australia\Block\Payment\DirectDeposit\Form */ ?>

<fieldset class="admin__fieldset payment-method" id="payment_form_<?php echo $block->escapeHtml($block->getMethodCode()) ?>" style="display:none">
    <label class="label"><span><?php echo $block->escapeHtml(__("Account Name")); ?></span></label>: <?php echo $block->escapeHtml($block->getAccountName()); ?>
    <br>
    <label class="label"><span><?php echo $block->escapeHtml(__("Account BSB")); ?></span></label>: <?php echo $block->escapeHtml($block->getAccountBSB()); ?>
    <br>
    <label class="label"><span><?php echo $block->escapeHtml(__("Account Number")); ?></span></label>: <?php echo $block->escapeHtml($block->getAccountNumber()); ?>
</fieldset>
