<?php
/**
 * Fontis Australia Extension for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @copyright  Copyright (c) 2017 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php /** @var $block Fontis\Australia\Block\Payment\DirectDeposit\CheckoutSuccess */ ?>

<table class="data table">
    <caption class="table-caption"><?php echo $block->escapeHtml($block->getMethodTitle()); ?></caption>
    <?php if ($accountName = $block->getAccountName()): ?>
    <tr>
        <th scope="row"><?php echo $block->escapeHtml(__("Account Name")); ?></th>
        <td><?php echo $block->escapeHtml($accountName); ?></td>
    </tr>
    <?php endif; ?>
    <?php if ($accountBSB = $block->getAccountBSB()): ?>
    <tr>
        <th scope="row"><?php echo $block->escapeHtml(__("Account BSB")); ?></th>
        <td><?php echo $block->escapeHtml($accountBSB); ?></td>
    </tr>
    <?php endif; ?>
    <?php if ($accountNumber = $block->getAccountNumber()): ?>
    <tr>
        <th scope="row"><?php echo $block->escapeHtml(__("Account Number")); ?></th>
        <td><?php echo $block->escapeHtml($accountNumber); ?></td>
    </tr>
    <?php endif; ?>
    <?php if ($message = $block->getMessage()): ?>
    <tr>
        <td colspan="2"><p><?php echo $block->escapeHtml($message); ?></p></td>
    </tr>
    <?php endif; ?>
</table>
