<?php
/**
 * Fontis Australia Extension for Magento 2
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.txt.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 *
 * @category   Fontis
 * @package    Fontis_Australia
 * @copyright  Copyright (c) 2017 Fontis Pty. Ltd. (https://www.fontis.com.au)
 * @license    https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 */
?>
<?php
/** @var $block Fontis\Australia\Block\Payment\DirectDeposit\Form */
$methodCode = $block->escapeHtml($block->getMethodCode());
?>
<div class="items <?php echo $methodCode; ?> instructions agreement checkout-agreement-item-content" id="payment_form_<?php echo $methodCode ?>" style="display: none;">
    <ul>
        <li><?php echo $block->escapeHtml(__("Account Name: %1", $block->getAccountName())); ?></li>
        <li><?php echo $block->escapeHtml(__("Account BSB: %1", $block->getAccountBSB())); ?></li>
        <li><?php echo $block->escapeHtml(__("Account Number: %1", $block->getAccountNumber())); ?></li>
        <?php if ($message = $block->getMessage()): ?>
        <li><p><?php echo $block->escapeHtml($message); ?></p></li>
        <?php endif; ?>
    </ul>
</div>
